server:
  port: 8888
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://ikematsu.com.br,http://localhost:80
file:
  upload-dir: /Code/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_springboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true